--password-store=gnome-libsecret
--enable-features=AcceleratedVideoDecodeLinuxGL,AcceleratedVideoEncoder,VaapiVideoDecoder,VaapiOnNvidiaGPUs
--ignore-gpu-blocklist
--disable-gpu-driver-bug-workaround
