# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  source-cnws = {
    pname = "source-cnws";
    version = "fd2e711dc7fd957267df5056a57575b3eb090ac4";
    src = fetchFromGitHub {
      owner = "kanglmf";
      repo = "emacs-chinese-word-segmentation";
      rev = "fd2e711dc7fd957267df5056a57575b3eb090ac4";
      fetchSubmodules = true;
      sha256 = "sha256-TnlrAA3KuQsBvmcc7yk0IKLpaSyJg8e1wGKBbF5b9pI=";
    };
    date = "2025-09-03";
  };
  source-emacs-lsp-booster = {
    pname = "source-emacs-lsp-booster";
    version = "004bb508c9a2d2877b9145fcccd5437f23a0b669";
    src = fetchFromGitHub {
      owner = "blahgeek";
      repo = "emacs-lsp-booster";
      rev = "004bb508c9a2d2877b9145fcccd5437f23a0b669";
      fetchSubmodules = false;
      sha256 = "sha256-aOkvOyRlkG7gzMy5/x15CMm/voOFOX98QcWVbvfuVLM=";
    };
    date = "2026-04-12";
  };
  source-emacs-master = {
    pname = "source-emacs-master";
    version = "d0653b46f65d340ad464e318e06d301380091bc0";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "d0653b46f65d340ad464e318e06d301380091bc0";
      fetchSubmodules = false;
      sha256 = "sha256-35Qc9yoZVKqsynM5+cbMaYKzNy0q/5nT/WF4VDi2QFE=";
    };
    date = "2026-06-10";
  };
  source-emacs-master-igc = {
    pname = "source-emacs-master-igc";
    version = "18548c4b25fd2769fc30f44bea5bc1a03153036e";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "18548c4b25fd2769fc30f44bea5bc1a03153036e";
      fetchSubmodules = false;
      sha256 = "sha256-+/ZUa8pmqShwiCtPiQ1EHKRY3nSbzFr+osY10dq0slU=";
    };
    date = "2026-06-09";
  };
  source-librime-charcode = {
    pname = "source-librime-charcode";
    version = "55e7f563e999802d41a13ba02657c1be4b2011b4";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "librime-charcode";
      rev = "55e7f563e999802d41a13ba02657c1be4b2011b4";
      fetchSubmodules = false;
      sha256 = "sha256-KfKkpph+2ChQpkkGKubmpg/18uPX9qUHTqJT1PSGorI=";
    };
    date = "2024-03-19";
  };
  source-librime-lua = {
    pname = "source-librime-lua";
    version = "ec52e48ea18f11af37717a01c337f853215cf70b";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "ec52e48ea18f11af37717a01c337f853215cf70b";
      fetchSubmodules = false;
      sha256 = "sha256-ipqsYAqlt29dZlgynziCC4rHFDbXsD64KPkhXQiz8/w=";
    };
    date = "2026-05-02";
  };
  source-librime-octagram = {
    pname = "source-librime-octagram";
    version = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-octagram";
      rev = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
      fetchSubmodules = false;
      sha256 = "sha256-dgUsH10V87mEcX/k3N118qbKo3fKDFcS8inhS6p5bJc=";
    };
    date = "2024-11-18";
  };
  source-librime-proto = {
    pname = "source-librime-proto";
    version = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-proto";
      rev = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
      fetchSubmodules = false;
      sha256 = "sha256-HdypebfmzreSdEQBwbvRG6sJZPASP+e8Tew+GrMnpOQ=";
    };
    date = "2023-10-17";
  };
  source-spicetify-cli = {
    pname = "source-spicetify-cli";
    version = "v2.43.2";
    src = fetchFromGitHub {
      owner = "spicetify";
      repo = "cli";
      rev = "v2.43.2";
      fetchSubmodules = false;
      sha256 = "sha256-77OZVDtybkYI5R3tZ7q2cLJ+Ixn8WB4CP4qP6Yp535g=";
    };
  };
  source-zsh-jovial-theme = {
    pname = "source-zsh-jovial-theme";
    version = "426fe1fb612e85817ec23440a64f2732b8d34b3f";
    src = fetchFromGitHub {
      owner = "zthxxx";
      repo = "jovial";
      rev = "426fe1fb612e85817ec23440a64f2732b8d34b3f";
      fetchSubmodules = false;
      sha256 = "sha256-VvF1alXCLatkSDJGImxFkijiVwtOGYgH1gXlqLfgWcs=";
    };
    date = "2026-05-12";
  };
}
