# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  patches-telegram = {
    pname = "patches-telegram";
    version = "36e27074851c64e52706adc606d1a9bfc12a3194";
    src = fetchFromGitHub {
      owner = "Layerex";
      repo = "telegram-desktop-patches";
      rev = "36e27074851c64e52706adc606d1a9bfc12a3194";
      fetchSubmodules = false;
      sha256 = "sha256-TRtlh/ExnS4li1JVgreRguboUZeLe8hH4RiJCPobPNw=";
    };
    date = "2025-01-10";
  };
  source-64gram = {
    pname = "source-64gram";
    version = "547bba18dfaceb3888d60ac1d2c16d0b7acdad46";
    src = fetchFromGitHub {
      owner = "TDesktop-x64";
      repo = "tdesktop";
      rev = "547bba18dfaceb3888d60ac1d2c16d0b7acdad46";
      fetchSubmodules = true;
      sha256 = "sha256-RHybrvm5p8BUt5StT/NuR76f2y1CCICirTMjdeRLtkY=";
    };
    date = "2025-01-11";
  };
  source-emacs-lsp-booster = {
    pname = "source-emacs-lsp-booster";
    version = "5f702a2699f306a3958ff1996a2b1a625f0cee0b";
    src = fetchFromGitHub {
      owner = "blahgeek";
      repo = "emacs-lsp-booster";
      rev = "5f702a2699f306a3958ff1996a2b1a625f0cee0b";
      fetchSubmodules = false;
      sha256 = "sha256-R9v+hCma/FfYdR+fvZ0vmtVk4dm+bPBacwV1QCc6X+8=";
    };
    date = "2025-01-07";
  };
  source-emacs-master = {
    pname = "source-emacs-master";
    version = "a00e6e7143d5ebf7282b5e5b410e1bd882634d57";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "a00e6e7143d5ebf7282b5e5b410e1bd882634d57";
      fetchSubmodules = false;
      sha256 = "sha256-Ydf51Y0n+MvCUZFB6MyuWTC32vRBLvHWW8Ht5VsqI0M=";
    };
    date = "2025-01-24";
  };
  source-emacs-master-igc = {
    pname = "source-emacs-master-igc";
    version = "7146d10b4625043d8e36dd91ff1574568158dc55";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "7146d10b4625043d8e36dd91ff1574568158dc55";
      fetchSubmodules = false;
      sha256 = "sha256-rwGQnRPrhTdiVE37jb83LWaCONpW9aZ1E+/yaMrBw10=";
    };
    date = "2025-01-23";
  };
  source-librime-charcode = {
    pname = "source-librime-charcode";
    version = "55e7f563e999802d41a13ba02657c1be4b2011b4";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "librime-charcode";
      rev = "55e7f563e999802d41a13ba02657c1be4b2011b4";
      fetchSubmodules = false;
      sha256 = "sha256-KfKkpph+2ChQpkkGKubmpg/18uPX9qUHTqJT1PSGorI=";
    };
    date = "2024-03-19";
  };
  source-librime-lua = {
    pname = "source-librime-lua";
    version = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
      fetchSubmodules = false;
      sha256 = "sha256-zx0F41szn5qlc2MNjt1vizLIsIFQ67fp5cb8U8UUgtY=";
    };
    date = "2024-12-21";
  };
  source-librime-octagram = {
    pname = "source-librime-octagram";
    version = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-octagram";
      rev = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
      fetchSubmodules = false;
      sha256 = "sha256-dgUsH10V87mEcX/k3N118qbKo3fKDFcS8inhS6p5bJc=";
    };
    date = "2024-11-18";
  };
  source-librime-proto = {
    pname = "source-librime-proto";
    version = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-proto";
      rev = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
      fetchSubmodules = false;
      sha256 = "sha256-HdypebfmzreSdEQBwbvRG6sJZPASP+e8Tew+GrMnpOQ=";
    };
    date = "2023-10-17";
  };
  source-spicetify-cli = {
    pname = "source-spicetify-cli";
    version = "cfda93b30bcdab47dca26b5f0570dae8b0c8660d";
    src = fetchFromGitHub {
      owner = "spicetify";
      repo = "cli";
      rev = "cfda93b30bcdab47dca26b5f0570dae8b0c8660d";
      fetchSubmodules = false;
      sha256 = "sha256-v926mpvKhEB8eQmE8hDPhRQq6Odt5hV8nRvGe3nRvY0=";
    };
    date = "2025-01-24";
  };
  source-zsh-jovial-theme = {
    pname = "source-zsh-jovial-theme";
    version = "6cedfe232c55b7f0bc599e0bd328f01bfe55b29b";
    src = fetchFromGitHub {
      owner = "zthxxx";
      repo = "jovial";
      rev = "6cedfe232c55b7f0bc599e0bd328f01bfe55b29b";
      fetchSubmodules = false;
      sha256 = "sha256-KTsrbHDACFiIn1mWOwphFb4NaBqZKrqloZ2K8mnzqpc=";
    };
    date = "2024-07-14";
  };
}
