# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  source-emacs-lsp-booster = {
    pname = "source-emacs-lsp-booster";
    version = "59f42abb419829f5bcde103d0b18616779ea05f3";
    src = fetchFromGitHub {
      owner = "blahgeek";
      repo = "emacs-lsp-booster";
      rev = "59f42abb419829f5bcde103d0b18616779ea05f3";
      fetchSubmodules = false;
      sha256 = "sha256-xAkYVzDf5fRUQQf3qZ5jicngPemfGdbDknjawlz/A+Q=";
    };
    date = "2024-11-30";
  };
  source-emacs-master = {
    pname = "source-emacs-master";
    version = "43b81b7ecaf465eef268dd2cd94f00a0c4da87ea";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "43b81b7ecaf465eef268dd2cd94f00a0c4da87ea";
      fetchSubmodules = false;
      sha256 = "sha256-CDUAE8apvejLrbWk9KdKkJNlt8OXpAsVcLqev97TJLE=";
    };
    date = "2024-12-27";
  };
  source-emacs-master-igc = {
    pname = "source-emacs-master-igc";
    version = "eedd4b7427d4f8d75d63cf68cc1cdfc851d6883b";
    src = fetchFromGitHub {
      owner = "emacs-mirror";
      repo = "emacs";
      rev = "eedd4b7427d4f8d75d63cf68cc1cdfc851d6883b";
      fetchSubmodules = false;
      sha256 = "sha256-mga3F006GOTKFJ1QpQ1gUmM3Hw6Wpj2WFB5Qq7lf39Y=";
    };
    date = "2024-12-26";
  };
  source-librime-charcode = {
    pname = "source-librime-charcode";
    version = "55e7f563e999802d41a13ba02657c1be4b2011b4";
    src = fetchFromGitHub {
      owner = "rime";
      repo = "librime-charcode";
      rev = "55e7f563e999802d41a13ba02657c1be4b2011b4";
      fetchSubmodules = false;
      sha256 = "sha256-KfKkpph+2ChQpkkGKubmpg/18uPX9qUHTqJT1PSGorI=";
    };
    date = "2024-03-19";
  };
  source-librime-lua = {
    pname = "source-librime-lua";
    version = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
    src = fetchFromGitHub {
      owner = "hchunhui";
      repo = "librime-lua";
      rev = "e3912a4b3ac2c202d89face3fef3d41eb1d7fcd6";
      fetchSubmodules = false;
      sha256 = "sha256-zx0F41szn5qlc2MNjt1vizLIsIFQ67fp5cb8U8UUgtY=";
    };
    date = "2024-12-21";
  };
  source-librime-octagram = {
    pname = "source-librime-octagram";
    version = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-octagram";
      rev = "dfcc15115788c828d9dd7b4bff68067d3ce2ffb8";
      fetchSubmodules = false;
      sha256 = "sha256-dgUsH10V87mEcX/k3N118qbKo3fKDFcS8inhS6p5bJc=";
    };
    date = "2024-11-18";
  };
  source-librime-proto = {
    pname = "source-librime-proto";
    version = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
    src = fetchFromGitHub {
      owner = "lotem";
      repo = "librime-proto";
      rev = "657a923cd4c333e681dc943e6894e6f6d42d25b4";
      fetchSubmodules = false;
      sha256 = "sha256-HdypebfmzreSdEQBwbvRG6sJZPASP+e8Tew+GrMnpOQ=";
    };
    date = "2023-10-17";
  };
  source-spicetify-cli = {
    pname = "source-spicetify-cli";
    version = "01f5cc5427627d83f08f16ad9fec9f1e69636532";
    src = fetchFromGitHub {
      owner = "spicetify";
      repo = "cli";
      rev = "01f5cc5427627d83f08f16ad9fec9f1e69636532";
      fetchSubmodules = false;
      sha256 = "sha256-2fsHFl5t/Xo7W5IHGc5FWY92JvXjkln6keEn4BZerw4=";
    };
    date = "2024-12-21";
  };
  source-zsh-jovial-theme = {
    pname = "source-zsh-jovial-theme";
    version = "6cedfe232c55b7f0bc599e0bd328f01bfe55b29b";
    src = fetchFromGitHub {
      owner = "zthxxx";
      repo = "jovial";
      rev = "6cedfe232c55b7f0bc599e0bd328f01bfe55b29b";
      fetchSubmodules = false;
      sha256 = "sha256-KTsrbHDACFiIn1mWOwphFb4NaBqZKrqloZ2K8mnzqpc=";
    };
    date = "2024-07-14";
  };
}
