[source-librime-charcode]
src.git = "https://github.com/rime/librime-charcode.git"
fetch.github = "rime/librime-charcode"

[source-librime-lua]
src.git = "https://github.com/hchunhui/librime-lua.git"
fetch.github = "hchunhui/librime-lua"

[source-librime-octagram]
src.git = "https://github.com/lotem/librime-octagram.git"
fetch.github = "lotem/librime-octagram"

[source-librime-proto]
src.git = "https://github.com/lotem/librime-proto.git"
fetch.github = "lotem/librime-proto"

[source-emacs-lsp-booster]
src.git = "https://github.com/blahgeek/emacs-lsp-booster"
fetch.github = "blahgeek/emacs-lsp-booster"

[source-zsh-jovial-theme]
src.git = "https://github.com/zthxxx/jovial.git"
fetch.github = "zthxxx/jovial"

[source-emacs-master]
src.git = "https://github.com/emacs-mirror/emacs.git"
fetch.github = "emacs-mirror/emacs"

[source-emacs-master-igc]
src.git = "https://github.com/emacs-mirror/emacs.git"
src.branch = "feature/igc3"
fetch.github = "emacs-mirror/emacs"

[source-spicetify-cli]
src.github = "spicetify/cli"
fetch.github = "spicetify/cli"

[source-cnws]
src.git = "https://github.com/kanglmf/emacs-chinese-word-segmentation"
fetch.github = "kanglmf/emacs-chinese-word-segmentation"
git.fetchSubmodules = true
