[env]
SDKMAN_DIR = "$HOME/.sdkman"

[tasks]
generate_fake_sdkman.run = """
ls=/usr/bin/ls
src="$HOME/.local/share/mise/installs/java"
dst="$HOME/.sdkman/candidates/java"
mkdir -p $dst
for v in $($ls -1 "$src" | grep -E '^[[:alpha:]][[:alnum:]-]*-[0-9]+$'); do
    ln -sfn "$src/$v" "$dst/$v"
done
"""

[hooks]
postinstall = [ {task = "generate_fake_sdkman"} ]
